#!/usr/bin/env node
// Copyright (c) cdktn-io
// SPDX-License-Identifier: MPL-2.0
/**
 * Builds `mini-schema.json` + `mini-groups.json`, the fixture the contract tests run against, by
 * slicing the pinned 34 MB `schemas/schema.json` down to a handful of deliberately chosen entries.
 *
 * Deterministic: the selection is a hardcoded, sorted list of schema names, the output is
 * `JSON.stringify(..., 2)` over objects built in sorted key order, and nothing is re-formatted.
 * Re-running it on the same pin produces a byte-identical file, which is what `--check` asserts.
 *
 * The fixture is committed; `schemas/schema.json` is not. Every entry earns its place:
 *
 *  | entry                          | why |
 *  | ---                            | --- |
 *  | `aws_lb`                       | the canonical target of the alias below; medium nesting |
 *  | `aws_alb`                      | an ALIAS — a real schema resource with its own full block, which must be generated as its own class inside `aws_lb`'s group |
 *  | `aws_lambda_function`          | deep nesting (14 nested block types) — exercises the namespace mount and the collision fallback |
 *  | `aws_lambda_permission`        | reserved-word-ish attributes: a `timeouts` block with `create`/`delete` (`delete` is a Go keyword) |
 *  | data `aws_lb`                  | a data source, which the awscc fork this generator was taken from could not emit at all |
 *  | ephemeral `aws_lambda_invocation` | an ephemeral resource — proves the vendored 0.24 machinery supports the third surface |
 *  | the `provider` block           | the AwsProvider construct, incl. its Python-reserved `lambda` attribute |
 *  | the `functions` section        | all four provider-defined functions — three `string` returns and `arn_parse`'s `object` return, which is the only one the emitter maps to a bare `cdktn.IResolvable` |
 *
 * Usage: node extract-fixture.mjs [--check]
 */
import { readFileSync, writeFileSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..", "..", "..", "..");

const AWS_FQPN = "registry.terraform.io/hashicorp/aws";

export const FIXTURE_RESOURCES = ["aws_alb", "aws_lambda_function", "aws_lambda_permission", "aws_lb"];
export const FIXTURE_DATA_SOURCES = ["aws_lb"];
export const FIXTURE_EPHEMERAL = ["aws_lambda_invocation"];

const schemaPath =
  process.env.CDKTN_AWS_SCHEMA ?? path.join(repoRoot, "schemas", "schema.json");

function pick(source, names, label) {
  const out = {};
  for (const name of [...names].sort()) {
    if (!source?.[name]) throw new Error(`${label}: pinned schema has no entry "${name}"`);
    out[name] = source[name];
  }
  return out;
}

const full = JSON.parse(readFileSync(schemaPath, "utf-8"));
const aws = full.provider_schemas?.[AWS_FQPN];
if (!aws) throw new Error(`${schemaPath}: no provider_schemas["${AWS_FQPN}"]`);

const pinnedProviderVersion = readFileSync(
  path.join(repoRoot, "schemas", "PROVIDER_VERSION"),
  "utf-8",
).trim();

/**
 * `provider_versions` is NOT a key `terraform providers schema -json` emits — the dump records no
 * version at all. `src/schema.ts#loadAwsSchema` synthesizes it from `schemas/PROVIDER_VERSION`
 * for every real run, so the fixture has to carry it too: the tests load `mini-schema.json`
 * directly, and without this key every emitted doc link degrades to `/aws/latest/docs` and
 * `terraformGeneratorMetadata.providerVersion` to `"latest"` — i.e. the snapshots would pin a
 * shape `pnpm generate` never produces.
 */
const miniSchema = {
  format_version: full.format_version,
  provider_versions: { [AWS_FQPN]: full.provider_versions?.[AWS_FQPN] ?? pinnedProviderVersion },
  provider_schemas: {
    [AWS_FQPN]: {
      provider: aws.provider,
      // All four; there is nothing to slice. `functions` is a provider-scoped sibling of
      // `provider`, not a per-resource surface (their doc pages all carry `subcategory: ""`), so
      // it belongs to the synthetic `provider` group rather than to any service group.
      functions: aws.functions,
      resource_schemas: pick(aws.resource_schemas, FIXTURE_RESOURCES, "resource_schemas"),
      data_source_schemas: pick(aws.data_source_schemas, FIXTURE_DATA_SOURCES, "data_source_schemas"),
      ephemeral_resource_schemas: pick(
        aws.ephemeral_resource_schemas,
        FIXTURE_EPHEMERAL,
        "ephemeral_resource_schemas",
      ),
    },
  },
};

/**
 * A self-contained groups file for the fixture. `aws_alb` is deliberately NOT listed: it is an
 * alias, and the generator has to place it in `elb` by resolving the alias table — exactly the
 * way it does against the real groups.json.
 */
const miniGroups = {
  $comment: "Fixture for tools/aws2cdk contract tests. Generated by extract-fixture.mjs.",
  pinnedProviderVersion,
  pinnedProviderTag: `v${pinnedProviderVersion}`,
  groups: {
    elb: { title: "ELB (Elastic Load Balancing)", resources: ["aws_lb"], dataSources: ["aws_lb"], ephemeralResources: [] },
    lambda: {
      title: "Lambda",
      resources: ["aws_lambda_function", "aws_lambda_permission"],
      dataSources: [],
      ephemeralResources: ["aws_lambda_invocation"],
    },
  },
  aliases: { aws_alb: "aws_lb" },
};

const targets = [
  [path.join(here, "mini-schema.json"), `${JSON.stringify(miniSchema, null, 2)}\n`],
  [path.join(here, "mini-groups.json"), `${JSON.stringify(miniGroups, null, 2)}\n`],
];

if (process.argv.includes("--check")) {
  let bad = 0;
  for (const [file, text] of targets) {
    const current = readFileSync(file, "utf-8");
    if (current !== text) {
      console.error(`${path.relative(repoRoot, file)} is stale — re-run extract-fixture.mjs`);
      bad++;
    }
  }
  if (bad > 0) process.exit(1);
  console.log("fixtures up to date");
} else {
  for (const [file, text] of targets) {
    writeFileSync(file, text);
    console.log(`wrote ${path.relative(repoRoot, file)} (${text.length} bytes)`);
  }
}
