import { readFileSync } from "node:fs";
import { groupsJsonPath } from "./paths.js";
import { SURFACES, type Group, type GroupsFile, type SurfaceKind } from "./types.js";

export function readGroupsFile(file = groupsJsonPath): GroupsFile {
  return parseGroupsFile(readFileSync(file, "utf-8"), file);
}

export function parseGroupsFile(text: string, label = "groups.json"): GroupsFile {
  const parsed = JSON.parse(text) as Partial<GroupsFile>;
  if (!parsed.groups || typeof parsed.groups !== "object") {
    throw new Error(`${label}: missing "groups" object`);
  }
  return {
    pinnedProviderVersion: parsed.pinnedProviderVersion ?? "",
    pinnedProviderTag: parsed.pinnedProviderTag ?? "",
    groups: parsed.groups as Record<string, Group>,
    aliases: parsed.aliases ?? {},
  };
}

/**
 * Deterministic serialization: slugs sorted, group keys in a fixed order,
 * every name array sorted, aliases sorted. Two runs over the same inputs must
 * produce a byte-identical file so that `git diff` only ever shows real change.
 */
export function serializeGroupsFile(g: GroupsFile): string {
  const groups: Record<string, Group> = {};
  for (const slug of Object.keys(g.groups).sort()) {
    const src = g.groups[slug];
    groups[slug] = {
      title: src.title,
      resources: [...src.resources].sort(),
      dataSources: [...src.dataSources].sort(),
      ephemeralResources: [...src.ephemeralResources].sort(),
    };
  }
  const aliases: Record<string, string> = {};
  for (const name of Object.keys(g.aliases).sort()) aliases[name] = g.aliases[name];

  return `${JSON.stringify(
    {
      $comment:
        "Generated by tools/mine-groups, then curated by hand. THIS FILE IS THE SOURCE OF TRUTH; " +
        "the miner only proposes diffs. Human decisions live in mine-config.json. " +
        "Gate: pnpm check:groups. See docs/curation.md.",
      pinnedProviderVersion: g.pinnedProviderVersion,
      pinnedProviderTag: g.pinnedProviderTag,
      groups,
      aliases,
    },
    null,
    2,
  )}\n`;
}

export interface OwnerIndex {
  /** surface -> canonical name -> slug that lists it. */
  bySurface: Record<SurfaceKind, Map<string, string>>;
  /** surface -> name listed in more than one group -> the slugs listing it. */
  duplicates: Record<SurfaceKind, Map<string, string[]>>;
}

/** Builds name -> owning-slug maps, recording duplicates instead of throwing. */
export function indexGroups(g: GroupsFile): OwnerIndex {
  const bySurface = {} as OwnerIndex["bySurface"];
  const duplicates = {} as OwnerIndex["duplicates"];
  for (const surface of SURFACES) {
    bySurface[surface] = new Map();
    duplicates[surface] = new Map();
  }

  for (const slug of Object.keys(g.groups).sort()) {
    for (const surface of SURFACES) {
      for (const name of g.groups[slug][surface] ?? []) {
        const owner = bySurface[surface];
        if (owner.has(name)) {
          const seen = duplicates[surface].get(name) ?? [owner.get(name)!];
          seen.push(slug);
          duplicates[surface].set(name, seen);
        } else {
          owner.set(name, slug);
        }
      }
    }
  }
  return { bySurface, duplicates };
}

/**
 * The group a schema name belongs to: either it is listed directly, or it is an
 * alias and inherits the group of its canonical target (aliases are never
 * listed in a group's arrays — see docs/curation.md, "Alias representation").
 * Alias chains are followed, with a cycle guard.
 */
export function groupOf(
  g: GroupsFile,
  index: OwnerIndex,
  surface: SurfaceKind,
  name: string,
): string | undefined {
  const seen = new Set<string>();
  let cur = name;
  for (;;) {
    const direct = index.bySurface[surface].get(cur);
    if (direct) return direct;
    const target = g.aliases[cur];
    if (!target || seen.has(cur)) return undefined;
    seen.add(cur);
    cur = target;
  }
}
