// Copyright (c) cdktn-io
// SPDX-License-Identifier: MPL-2.0
/**
 * The per-group STANDALONE jsii package manifest. Shape and every field here come from the
 * go-split-spike verdict (Option A) and its working template, `option-a/gen-packages.js`:
 * one `jsii` compile + one `jsii-pacmak --targets go` per group, output consumed verbatim.
 *
 * Two deliberate departures from that prototype template:
 *
 *  - `cdktn`/`constructs` are peerDependencies MIRRORED into **devDependencies**, not into
 *    `dependencies`. A jsii package that lists a peer as a runtime dependency draws JSII6
 *    ("a peer dependency should also be a devDependency" is the rule jsii actually enforces), and
 *    a real `dependencies` entry would additionally make each of 257 packages claim to own a copy
 *    of the runtime.
 *  - a per-group `README.md` is written, because jsii emits JSII3 ("there is no README.md file")
 *    otherwise. 257 machine-generated READMEs is exactly the cost VERDICT §4 books against
 *    Option A; this is where it is paid.
 */
import { GroupMembers, goPackageName, npmPackageName } from "./groups";

export const GO_MODULE_ROOT = "github.com/cdktn-io/cdktn-aws-go";
export const CDKTN_VERSION = "^0.24.0";
export const CONSTRUCTS_VERSION = "^10.7.0";
/** Exact pins for the devDependency mirror — a range there resolves to whatever is in the lock. */
export const CDKTN_PIN = "0.24.0";
export const CONSTRUCTS_PIN = "10.7.0";

export interface ManifestOptions {
  readonly version: string;
  readonly providerVersion: string;
}

export function packageJsonFor(group: GroupMembers, opts: ManifestOptions): unknown {
  return {
    name: npmPackageName(group.slug),
    version: opts.version,
    // NEVER published to npm. The Go distribution embeds the .jsii assembly + a tarball of this
    // package; that tarball is the runtime, so publishing would only create a second, divergent
    // copy. See go-split-spike/VERDICT.md §3.
    private: true,
    description: `cdk-terrain bindings for the ${group.title} group of terraform-provider-aws ${opts.providerVersion}`,
    license: "MPL-2.0",
    author: { name: "cdktn-io", organization: true },
    repository: { type: "git", url: "https://github.com/cdktn-io/cdktn-aws.git" },
    stability: "experimental",
    main: "lib/index.js",
    types: "lib/index.d.ts",
    jsii: {
      outdir: "dist",
      versionFormat: "short",
      tsc: { outDir: "lib", rootDir: "src" },
      targets: {
        // module path = moduleName + "/" + packageName
        //            => github.com/cdktn-io/cdktn-aws-go/<goPackageName>
        // packageName is the ONLY per-group Go knob: it is the directory in that repo and the
        // prefix of this module's release tags.
        go: { moduleName: GO_MODULE_ROOT, packageName: goPackageName(group.slug) },
      },
    },
    peerDependencies: { cdktn: CDKTN_VERSION, constructs: CONSTRUCTS_VERSION },
    devDependencies: { cdktn: CDKTN_PIN, constructs: CONSTRUCTS_PIN },
  };
}

export function readmeFor(group: GroupMembers, opts: ManifestOptions): string {
  const counts = [
    `${group.resources.length} resource${group.resources.length === 1 ? "" : "s"}`,
    `${group.dataSources.length} data source${group.dataSources.length === 1 ? "" : "s"}`,
    ...(group.ephemeralResources.length > 0
      ? [`${group.ephemeralResources.length} ephemeral resource${group.ephemeralResources.length === 1 ? "" : "s"}`]
      : []),
  ].join(", ");

  return `# ${npmPackageName(group.slug)}

cdk-terrain bindings for the **${group.title}** group of \`terraform-provider-aws\`
${opts.providerVersion} — ${counts}.

Generated by \`tools/aws2cdk\` from the pinned provider schema and the repo-root \`groups.json\`.
Do not edit by hand.

This package is \`private: true\` and is never published to npm. It exists to be compiled by
\`jsii\` and packed by \`jsii-pacmak\`; the Go distribution is
\`${GO_MODULE_ROOT}/${goPackageName(group.slug)}\`.

Every construct here needs an \`AwsProvider\` in the same stack — see \`@cdktn/aws-provider\`.
`;
}

/**
 * The package's own tsconfig, committed alongside the sources.
 *
 * jsii normally writes this file itself and refuses to run when one it did not generate is
 * present. The generated packages instead pass `--tsconfig tsconfig.json --validate-tsconfig
 * generated`, jsii's own "full ownership over the file, but stay compatible with what
 * --generate-tsconfig would have written" mode — so the options below mirror jsii's generated
 * config exactly, and jsii itself enforces that they keep doing so.
 *
 * `incremental` is required by that rule set, so the build info it writes
 * (`lib/tsconfig.tsbuildinfo`) is gitignored along with the rest of `lib/`.
 *
 * Committing it means the exact options jsii compiles with are visible in review and are the same
 * ones `tsc --noEmit` uses for acceptance B — one file, not two that can drift.
 */
export function tsconfigFor(): unknown {
  return {
    compilerOptions: {
      outDir: "lib",
      rootDir: "src",
      declarationMap: false,
      inlineSourceMap: true,
      inlineSources: true,
      alwaysStrict: true,
      declaration: true,
      incremental: true,
      tsBuildInfoFile: "lib/tsconfig.tsbuildinfo",
      lib: ["es2020"],
      module: "commonjs",
      noEmitOnError: true,
      noFallthroughCasesInSwitch: true,
      noImplicitAny: true,
      noImplicitReturns: true,
      noImplicitThis: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      resolveJsonModule: true,
      skipLibCheck: true,
      strict: true,
      strictNullChecks: true,
      strictPropertyInitialization: true,
      stripInternal: false,
      target: "es2020",
      composite: false,
    },
    include: ["src/**/*.ts"],
    exclude: ["node_modules"],
  };
}
