// Copyright (c) cdktn-io
// SPDX-License-Identifier: MPL-2.0
/**
 * `naming-map.json` — the rename table from `@cdktn/provider-aws` (the classic per-resource cdktn
 * library, generated by the unmodified cdk-terrain pipeline) to `@cdktn/aws` 0.2.0.
 *
 * One entry per generated schema entry, keyed by the surface-marked terraform type (`aws_s3_bucket`
 * and `data_aws_s3_bucket` are two different classes and two different keys). It exists for two
 * readers: the migration tool, which needs the classic identity of a symbol a consumer already
 * imports, and the reviewer of the rename itself, for whom this file is the whole diff in one
 * place. The classic side is derived by running the vendored parser (see `classic-naming.ts`), not
 * by any rule restated here.
 *
 * It is emitted by a FULL `pnpm generate` only — a partial run would drop the other 250-odd groups
 * — and committed, for the same reason `generated/hashes.json` is.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { CLASSIC_ROOTS, ClassicName, ClassicNameIndex } from "./classic-naming";
import type { GenerateResult } from "./generate";

export const NAMING_MAP_FILE = "naming-map.json";

export interface NamingMapEntry {
  /** `resource` | `data_source` | `ephemeral_resource` | `provider` */
  readonly surface: string;
  readonly group: string;
  readonly className: string;
  /** where the same terraform type lives in `@cdktn/provider-aws`, per language */
  readonly classic: ClassicName;
}

export interface NamingMapFile {
  /** the classic library's package roots — the per-entry names hang off these */
  readonly classicRoots: typeof CLASSIC_ROOTS;
  readonly entries: Record<string, NamingMapEntry>;
}

export function buildNamingMap(result: GenerateResult, classic: ClassicNameIndex): NamingMapFile {
  const rows = result.groups.flatMap((g) =>
    g.entries.map((e) => {
      const identity = classic[e.parserType];
      // A generated entry with no classic counterpart means the two pipelines disagree about what
      // the schema contains — the map would silently lose a migration row, so stop.
      if (!identity) {
        throw new Error(`naming map: no @cdktn/provider-aws identity for "${e.parserType}"`);
      }
      return {
        key: e.parserType,
        value: { surface: e.schemaType, group: g.slug, className: e.className, classic: identity },
      };
    }),
  );
  const entries: Record<string, NamingMapEntry> = {};
  for (const row of rows.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0))) {
    entries[row.key] = row.value;
  }
  return { classicRoots: CLASSIC_ROOTS, entries };
}

export function writeNamingMap(dir: string, map: NamingMapFile): string {
  const file = path.join(dir, NAMING_MAP_FILE);
  fs.writeFileSync(file, `${JSON.stringify(map, null, 2)}\n`);
  return file;
}

export function readNamingMap(dir: string): NamingMapFile {
  return JSON.parse(fs.readFileSync(path.join(dir, NAMING_MAP_FILE), "utf-8"));
}
